---

# installing nfs on master
- name: creating directory /srv/nfs
  file: 
   path: /srv/nfs 
   state: directory 
- name: copying to /etc/exports
  copy: 
   src: exports
   dest: /etc/exports 
- name: start service
  systemd:
    name: nfs-server
    state: started
    enabled: yes
    masked: no
- name: apply the new configuration exportfs -r
  command: exportfs -r
- name: apply the new configuration exportfs -s
  command: exportfs -s
- name: make services accessible
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - nfs
    - rpc-bind
    - mountd
- name: reboot firewall
  command: firewall-cmd --reload