---
# full list of commands available here: https://github.com/jadebustos/devopslabs/blob/master/labs-k8s/00-00-instalando-kubernetes.md
# common configurations to both machines - second part
- name: modprobe
  modprobe:
    name: br_netfilter
    state: present
  become: yes
- name: set transparent masquerading
  firewalld: 
    masquerade: yes 
    permanent: true 
    zone: public
    state: enabled
- name: reboot firewall
  command: firewall-cmd --reload
- name: allow traffic management
  copy: 
   src: k8s.conf
   dest: "/etc/sysctl.d/k8s.conf"
- name: applying changes
  command: sysctl --system
- name: kubernetes YUM repository
  yum_repository:
    name: Kubernetes
    description: official repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kubelet kubeadm kubectl
  become: yes
- name: kubernetes instalation
  dnf:
    name: "{{ item }}"
    state: present
    disable_excludes: Kubernetes
  become: yes
  with_items: 
    - kubelet
    - kubeadm 
    - kubectl
- name: Initiating and enabling kubelet service permanently 
  systemd:
    name: kubelet
    state: started
    enabled: yes
    masked: no
  become: yes