---
# full list of commands available here: https://github.com/jadebustos/devopslabs/blob/master/labs-k8s/00-00-instalando-kubernetes.md
# configuring kubernetes on master
- name: setting up firewall in order to access to the kubernetes services
  firewalld:
    port: "{{item}}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
    - 6443/tcp  # Kubernetes API Server
    - 2379/tcp  # etcd server client API
    - 2380/tcp  # etcd server client API
    - 10250/tcp # Kubelet API
    - 10251/tcp # kube-scheduler
    - 10252/tcp # kube-controller-manager
    - 10255/tcp # Statistics
- name: reboot firewall
  command: firewall-cmd --reload
- name: configuring kubeadm
  command: kubeadm config images pull
- name: allow access from worker
  command: firewall-cmd --permanent --add-rich-rule 'rule family=ipv4 source address=192.168.1.111/32 accept'
- name: reboot firewall
  command: firewall-cmd --reload
- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr=192.169.0.0/16   
  register: result
  failed_when: "'Text file busy' in result.stdout"
- name: sleep for 20 seconds
  wait_for:
    timeout: 20
- name: Get token to join then worker 
  command: kubeadm token create --print-join-command
  register: kubernetes_join_command
- name: print token
  debug:
    var: kubernetes_join_command.stdout
- name: Copy join command to local file.
  become: no
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/Users/andreavidali/workspace/unircp2/ansible/kubernetes_join_command" mode=0777
- name: create .kube directory
  become: yes
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755
# - name: copy admin.conf to user's kube config
#   command: "cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
    